[theme]
base="dark"  # Or "light"
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"  # Options: "sans serif", "serif", or "monospace"